### ISSUE TITLE
[Bug] - Conflict with Rainbow Brackets PAID

### ISSUE THREAD

**Issue by nealculiner** [dinbtechit/vscode-theme#105]
I updated your Dark Modern theme for Rider and it requires rainbow brackets lite which I can't use because I have rainbow brackets PAID. So I can't use your theme now.

**Comment by dinbtechit** [comment]
Apologies for the inconvenience. This has been fixed in https://github.com/dinbtechit/vscode-theme/releases/tag/v1.10.1. Hopefully should be published by tomorrow.

Meanwhile, you Download the [latest release](https://github.com/dinbtechit/vscode-theme/releases/latest) and install it manually using
  <kbd>Settings/Preferences</kbd> > <kbd>Plugins</kbd> > <kbd>⚙️</kbd> > <kbd>Install plugin from disk...</kbd>

**Comment by nealculiner** [comment]
No worries, but IMHO I would not bundle them. People can install them as desired.
