### ISSUE TITLE
[Bug] - scroll bar is opaque

### ISSUE THREAD

**Issue by ursmeili** [dinbtechit/vscode-theme#11]
Rider 2022.2.EAP7 on Windows

The vertical scroll bar in an editor is opaque when VSCode Dark theme is used, which hides the warning/error indicators of Rider:

![grafik](https://user-images.githubusercontent.com/23562434/177331772-fafc9c93-2422-477f-86a4-80af23c2b26f.png)

Compare this with the scroll bar of the standard Rider Dark theme:
![grafik](https://user-images.githubusercontent.com/23562434/177332034-22116436-1abc-4fd9-84ba-92ef39f81791.png)

**Comment by dinbtechit** [comment]
Fixed in [1.5.4](https://github.com/dinbtechit/vscode-theme/releases/tag/v1.5.4). Might take a day or 2 to show up in the IDE plugins -> Marketplace.

## If you don't want to wait?

Download the [latest release](https://github.com/dinbtechit/vscode-theme/releases/latest) -> 📦[VSCode.Theme-X.X.X.zip] and install it manually using
  <kbd>Settings/Preferences</kbd> > <kbd>Plugins</kbd> > <kbd>⚙️</kbd> > <kbd>Install plugin from disk...</kbd>
