### ISSUE TITLE
[Bug] - Purple color is not the same as the one in VS Code

### ISSUE THREAD

**Issue by dannylol19** [dinbtechit/vscode-theme#47]
## Describe the bug
The purple color in the color scheme is not the same as the purple in vs code.
Purple from VS Code dark theme: **#C586C0**  
The purple you use in your theme is **#CE80B6**

## Platform & Language Details (please complete the following information):
- Platform: CLion
- Platform Version: 2022.3
- Language: [all] 
- Version [1.7.6]

## Jetbrains Screenshot
![image](https://user-images.githubusercontent.com/83356017/208075618-4ccd6828-6a0b-4ae8-b7b7-606520fcc891.png)

## VSCode Screenshot
![image](https://user-images.githubusercontent.com/83356017/208075241-dc14c730-9e38-4af8-917d-75bde52a89ae.png)

**Comment by dinbtechit** [comment]
Thank you for reporting the bug. This is a conscious decision. For some reason, Jetbrains Editor UI renders some VSCode colors differently (perhaps something to do with the Jetbrains fonts?). Right now, we are trying to visually match the rendered colors to the vscode color. That's why some colors can be different in the `Settings` -> `Color Scheme`

I think we can revisit the problem again and see if we can get it fixed in just the `VScode Dark` theme. So it doesn't impact the brighter theme.

**Comment by dinbtechit** [comment]
Fixed in v1.7.7
