### ISSUE TITLE
[Bug] Import and variables colors Python

### ISSUE THREAD

**Issue by Ted-18** [dinbtechit/vscode-theme#71]
## Describe the bug

On python, variables and imports don't have colors, I don't know if this is normal but being dyslexic, without these colors I can't work on PyCharm. 

Do you have a solution?

## Platform & Language Details 
- Language: Python

## Jetbrains Screenshot
![image](https://github.com/dinbtechit/vscode-theme/assets/84779771/cc3b2a4d-a5e1-4a04-9113-7f0d2fba6f6d)

## VSCode Screenshot
![image](https://github.com/dinbtechit/vscode-theme/assets/84779771/b58d9d44-9adb-47bc-b742-b197cf595313)

## Additional context/Logs
--

**Comment by Ted-18** [comment]
## Another Example
![image](https://github.com/dinbtechit/vscode-theme/assets/84779771/f46a95c9-162f-4490-bdc8-086dfbd1dfb9)
![image](https://github.com/dinbtechit/vscode-theme/assets/84779771/6cc85895-041b-4461-a5f5-66d50d0c3634)

**Comment by dinbtechit** [comment]
Thank you for reporting this bug! This needs to be fixed ASAP! 

Can I ask you for a favour? Are you able to provide some example Python GitHub repository that covers all Python code concepts?

Cheers! 🙌🙌🙌

**Comment by Ted-18** [comment]
I don't know if this repo contains everything you need, but I imagine it's already very complete. 

https://github.com/Pycord-Development/pycord

**Comment by dinbtechit** [comment]
Yeah, I can understand why most themes would not want to support this because the JetBrains platform does not provide many options to work with. It needs some significant customization (We also gotta be careful so it does not affect the performance). 

It would be hard to use pycord repo as an example repo asit would be hard to address/test all the concepts in a methodical way, I was looking for something like this ->  https://github.com/trekhleb/learn-python, but I'm not a Python developer so I can't tell if that covers all the scenarios in Python.

**Comment by Ted-18** [comment]
I had a look and it seems to be the most complete repo. I haven't found anything better.

I imagine it takes a lot of time and energy to develop a completely customized theme. 😅

**Comment by dinbtechit** [comment]
Fixed in [v1.8.2](https://github.com/dinbtechit/vscode-theme/releases/tag/v1.8.2)

> Note - You might still note some inconsistencies but feel free to open separate issues from them.
